apiVersion: v1
kind: Plugin
metadata:
  author: shinelinxx
  name: Text2LangbotMsgChain
  repository: https://github.com/shinelinxx/Text2LangbotMsgChain
  version: 1.0.0
  description:
    en_US: Convert structured text responses to LangBot message chains
    zh_Hans: 将结构化文本响应转换为LangBot消息链
  label:
    en_US: Text to Message Chain
    zh_Hans: 文本转消息链
  icon: assets/icon.png
spec:
  config: []
  components:
    EventListener:
      fromDirs:
      - path: components/event_listener/
execution:
  python:
    path: main.py
    attr: Text2LangbotMsgChain
